language: php
php:
  - '5.6'
  - '7.1'
  - hhvm # on Trusty only
  - nightly

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)